services:
  kafka:
    build:
      context: ../../
      dockerfile: kafka-docker/Dockerfile
      network: host
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9101:9101"

  producer:
    build:
      context: ./producer
      network: host
    ports:
      - "5001:5000"
    depends_on:
      - kafka

  consumer-1:
    build:
      context: ./consumer
      network: host
    depends_on:
      - kafka

  consumer-2:
    build:
      context: ./consumer
      network: host
    depends_on:
      - kafka

  scraper:
    build:
      context: ../../scraper
      network: host
    depends_on:
      - kafka
