services:
  kafka:
    build:
      context: .
      dockerfile: kafka-docker/Dockerfile
    # image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9999:9999"
    environment:
      - JMX_PORT=9999
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999
    # environment:
    #   KAFKA_NODE_ID: 1
    #   KAFKA_PROCESS_ROLES: broker,controller
    #   KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

    #   KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT
    #   KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #   KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    #   ALLOW_PLAINTEXT_LISTENER: "yes"
    #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - kafka

  analyser:
    build:
      context: .
      dockerfile: analyser/Dockerfile
    container_name: analyser
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - JMX_HOST=kafka
      - JMX_PORT=9999
      - GROUP_ID=group1
      - TOPIC=test-topic
      - CONNECT_RETRY_MS=3000
      - POLL_INTERVAL_MS=5000