services:
  kafka:
    build:
      context: .
      dockerfile: kafka-docker/Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"   # Kafka broker (Admin API + client connections)
      - "9093:9093"   # KRaft controller
      - "9101:9101"   # Prometheus JMX Exporter — scraper reads from here

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - kafka
