services:
  kafka:
    build:
      context: ../../
      dockerfile: kafka-docker/Dockerfile
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
      - "9101:9101"

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka

  consumer-1:
    build:
      context: ./consumer
    ports:
      - "5001:5000"
    depends_on:
      - kafka

  consumer-2:
    build:
      context: ./consumer
    ports:
      - "5002:5000"
    depends_on:
      - kafka

  consumer-3:
    build:
      context: ./consumer
    ports:
      - "5003:5000"
    depends_on:
      - kafka

  consumer-4:
    build:
      context: ./consumer
    ports:
      - "5004:5000"
    depends_on:
      - kafka

  scraper:
    build:
      context: ../../scraper
    depends_on:
      - kafka
