process.roles=broker
node.id=2
controller.quorum.voters=1@kafka:9093
listeners=PLAINTEXT://kafka2:9092
inter.broker.listener.name=PLAINTEXT
advertised.listeners=PLAINTEXT://kafka2:9092
log.dirs=/tmp/kraft-broker-logs